package com.dss.tennis.tournament.tables.exception;

public enum ErrorConstants {

    //tournament errors
    TOURNAMENT_NAME_EMPTY,
    TOURNAMENT_NAME_DUPLICATE,
    TOURNAMENT_TYPE_EMPTY,
    PARTICIPANT_TYPE_EMPTY,
    TOURNAMENT_TYPE_NOT_SUPPORTED,
    TOURNAMENT_NOT_FOUND,
    FORBIDDEN_PARTICIPANT_QUANTITY,

    //contest errors

    //participant errors
    PLAYER_FIRST_NAME_EMPTY,
    PLAYER_LAST_NAME_EMPTY,
    PLAYER_NOT_FOUND,
    PLAYER_DUPLICATION,

    //participant warnings
    PARTICIPANT_DUPLICATION,
    PLAYER_DUPLICATION_IN_TOURNAMENT,
    TEAM_NOT_FOUND,

    //common errors
    UNSUPPORTED_RESOURCE_TYPE,
    GENERAL_BAD_REQUEST,
    INTERNAL_SERVER_ERROR,

    //common warnings
    REQUEST_PARAMETER_NOT_ALLOWED,
    PAGE_OUT_OF_LOWER_RANGE,
    PAGE_OUT_OF_UPPER_RANGE,
    PAGE_SIZE_OUT_OF_RANGE
}
