# This workflow will build API Package using Maven and then Deploy it to Test Environment

name: API Deploy Test
on:
  push:
    branches:
      - 'dev'
jobs:
  api-deploy-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Package with Maven
        run: mvn -B package -DskipTests --file ./api/pom.xml
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DSS_TENNIS_API_SECRET }}
          known_hosts: unnecessary
      - name: Deploy with rsync
        run: rsync -avz -e "ssh -oStrictHostKeyChecking=accept-new -p ${{ secrets.DSS_TENNIS_TEST_SSH_PORT }}" ./api/target/tournament.api-*.jar ${{ secrets.DSS_TENNIS_TEST_SSH_USER }}@${{ secrets.DSS_TENNIS_TEST_SSH_HOST }}:~/ua-com-dss-tennis/api/target/